### ISSUE TITLE
Hyphens and other characters in link labels

### ISSUE THREAD

**Issue by jenglish** [jsepia/markdown-it-wikilinks#2]
The regexp used for matching Wiki Links only recognizes alphanumeric characters, underscores, spaces, and forward slashes.  This leaves out a number of characters that could reasonably be expected to appear in link names; for example it would not recognize [[markdown-it-wikilinks]] as a valid link.

Not sure what the full set of characters should be, but hyphens and periods probably ought to be included at least.

**Comment by jsepia** [comment]
Fixed by #5
