### ISSUE TITLE
Replace will only replace the first whitespace

### ISSUE THREAD

**Issue by pstuifzand** [jsepia/markdown-it-wikilinks#3]
Hi,

the replace here will only replace the first whitespace in the name. The regex should be changed to `/\s+/g`.

https://github.com/jsepia/markdown-it-wikilinks/blob/79fe609a03917f7df11128231118a66a559076d0/index.js#L22

**Comment by jsepia** [comment]
Thanks for pointing this out. This feature is now in v1.3.0. Sorry it took me this long!
